name: PvpRestrictions
version: '1.0-SNAPSHOT'
main: hs.pvpRestrictions.PvpRestrictions
api-version: '1.21'
author: ___Pumpkinn
description: PvP restrictions

commands:
  endportals:
    description: Enable or disable end portals
    usage: /<command> [enable|disable|toggle|status]
    aliases: [endportal, ep]
    permission: pvprestrictions.endportals
    permission-message: You don't have permission to use this command!


permissions:
  pvprestrictions.endportals:
    description: Allows toggling end portals
    default: op

  pvprestrictions.*:
    description: All PvP restrictions permissions
    default: op
    children:
      pvprestrictions.endportals: true
